language: node_js
node_js:
  - "10.15.1"
cache: yarn
before_install:
  - yarn global add mocha truffle ganache-cli

before_script:

script:
  - yarn test:data
  - yarn test:api
  - yarn preptest:eth &
  - sleep 15
  - yarn test:eth